name: alver_shop
description: Ftuir shop on internet
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.2
  # flutter_carousel_widget: ^1.0.2
  carousel_slider: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/category/
    - assets/images/sliders/
    - assets/images/products/
    - assets/images/salads/
  fonts:
    - family: zona
      fonts:
        - asset: assets/fonts/Zona_Pro_Regular.otf
          weight: 400
        - asset: assets/fonts/Zona_Pro_SemiBold.otf
          weight: 600
        - asset: assets/fonts/Zona_Pro_Bold.otf
          weight: 700
        - asset: assets/fonts/Zona_Pro_ExtraBold.otf
          weight: 900